-- ============================================================
--  Interlanguage · Esquema de base de datos
-- ------------------------------------------------------------
--  La FUENTE DE VERDAD del esquema son las MIGRACIONES, en orden:
--     supabase/migrations/0001_init.sql   ← esquema inicial + RLS
--     supabase/migrations/0002_*.sql       ← cambios siguientes…
--
--  Para montar la base de datos desde cero:
--     Supabase → SQL Editor → pega el contenido de cada migración
--     (en orden) y pulsa Run. Empieza por 0001_init.sql.
--
--  Este archivo se conserva como puntero para evitar tener dos copias
--  del esquema que se desincronicen. Cuando la base esté estable, se
--  puede generar aquí un "snapshot" real con pg_dump --schema-only.
--
--  Modelo de datos (documentación):
--     docs/superpowers/specs/2026-07-29-modelo-datos-api.md
-- ============================================================
